---
title: "analisis_exploratorios"
author: "Alejandra Muñoz"
date: "13/3/2021"
output: 
  html_document: 
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE )
```

```{r}
# Cargar la biblioteca o paquete para leer archivos de Excel.
library(readxl)
library(tidyverse)

```

```{r}
# Lectura de la base de datos.
encuesta <- read.csv("encuesta1.csv")
```



```{r}
##Depuracion y adecuacion de la base de datos.
# Visualizar la estructura de la base de datos.
str(encuesta)
```

```{r}
encuesta<-encuesta %>%
  mutate_if(is.character, as.factor)
```

```{r}
glimpse(encuesta)
```

```{r}
#Formato fechas o Dates.
encuesta<-encuesta %>%
  mutate(Q02_FechaNac= as.Date(as.character(Q02_FechaNac),"%Y-%m-%d"))
```

```{r}
summary(encuesta$Q02_FechaNac)
```

```{r}
# Calculo de la edad
encuesta<-encuesta %>%
  mutate(Edad = as.numeric(as.Date("2021-06-30") - Q02_FechaNac)/365.25)
```

```{r}
# Conversion fecha-hora
encuesta<-encuesta %>%
  mutate(fecha_entrega= as.POSIXct(strptime(Enviado.el., format="%d/%m/%Y %H:%M:%S")), tiempo_usado= as.integer(format(fecha_entrega, "%M"))+ as.integer(format(fecha_entrega, "%S"))/ 60 -30)
```


```{r}
encuesta %>%
  filter(Q08_PAPA >5)
```

```{r}
# Cambio de la persona que puso 40, en vez de 4.0
encuesta$Q08_PAPA[encuesta$Q08_PAPA==45 & !is.na(encuesta$Q08_PAPA)] <- 4.5
```
```{r}
dotchart(encuesta$Q08_PAPA)
```



